

// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `mysql`
//     Provider:               `MySql.Data.MySqlClient`
//     Connection String:      `Server=192.168.2.251;Uid=zaiyunli;Pwd=zyl123654Aa;Database=THOA_BaseProduct;Port=3306;SslMode=none;`
//     Schema:                 ``
//     Include Views:          `False`















